version: '3.5'

services:
  proxy:
    container_name: nginx_lb
    build:
      context: ./builder
      dockerfile: Dockerfile
    volumes:
      - ./lb_php/:/etc/nginx/conf.d/
    ports: 
      - "8081:80"
    networks:
      docnet:
        ipv4_address: 172.10.1.20

  origin1:
    container_name: web1
    image: richarvey/nginx-php-fpm
    volumes: 
      - ./php1:/var/www/html/
    ports: 
      - "81:80"
    networks:
      docnet:
        ipv4_address: 172.10.1.21

  origin2:
    container_name: web2
    image: richarvey/nginx-php-fpm
    volumes: 
      - ./php2:/var/www/html/
    ports: 
      - "82:80"
    networks:
      docnet:
        ipv4_address: 172.10.1.22

  origin3:
    container_name: web3
    image: richarvey/nginx-php-fpm
    volumes: 
      - ./php3:/var/www/html/
    ports: 
      - "83:80"
    networks:
      docnet:
        ipv4_address: 172.10.1.23

networks:
  docnet:
    external: true