#Requires DE version 19.03.0+
version: '3.8'

services:
  proxy:
    container_name: nginx_lb
    build:
      context: ./builder
      dockerfile: Dockerfile
    volumes:
      - ./lb_php/:/etc/nginx/conf.d/
    ports: 
      - "8081:80"
    networks:
      - docnet

  origin1:
    container_name: web1
    image: richarvey/nginx-php-fpm
    volumes: 
      - ./php1:/var/www/html/
    ports: 
      - "81:80"
    networks:
      - docnet

  origin2:
    container_name: web2
    image: richarvey/nginx-php-fpm
    volumes: 
      - ./php2:/var/www/html/
    ports: 
      - "82:80"
    networks:
      - docnet

  origin3:
    container_name: web3
    image: richarvey/nginx-php-fpm
    volumes: 
      - ./php3:/var/www/html/
    ports: 
      - "83:80"
    networks:
      - docnet
  
  exporter:
    container_name: promEx
    image: nginx/nginx-prometheus-exporter:latest
    environment:
      - SCRAPE_URI=http://nginx_lb/api
      - TELEMETRY_PATH=/prometheus
      - NGINX_RETRIES=10
      - NGINX_PLUS=true
    networks:
      - docnet

  prom:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./p/p.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - docnet


networks:
  docnet:
    external: true